sudo: required

cache:
  directories:
    - ${HOME}/data

services:
  - docker

before_install:
  - export REPO_NAME=$( echo $TRAVIS_REPO_SLUG | cut -d'/' -f2 )
  - if [[ ! -d ~/data/ds114_test1 ]]; then travis_retry wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 -c -P ${HOME}/downloads/ "https://googledrive.com/host/0B2JWN60ZLkgkMEw4bW5VUUpSdFU/ds114_test1.tar" && mkdir -p ${HOME}/data && tar xf ${HOME}/downloads/ds114_test1.tar -C ${HOME}/data; fi
  - if [[ ! -d ~/data/ds114_test2 ]]; then travis_retry wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 -c -P ${HOME}/downloads/ "https://googledrive.com/host/0B2JWN60ZLkgkMEw4bW5VUUpSdFU/ds114_test2.tar" && mkdir -p ${HOME}/data && tar xf ${HOME}/downloads/ds114_test2.tar -C ${HOME}/data; fi
  - git describe --tags > version
  - docker build -t bids/${REPO_NAME,,} .
  - mkdir -p ${HOME}/outputs

script:
  # print version
  - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset bids/${REPO_NAME,,} --version
  # participant level tests for single session dataset
  - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs1:/outputs bids/${REPO_NAME,,} /bids_dataset /outputs participant --participant_label 01
  - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs1:/outputs bids/${REPO_NAME,,} /bids_dataset /outputs participant --participant_label 02
  # group level test for single session dataset
  - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test1:/bids_dataset -v ${HOME}/outputs1:/outputs bids/${REPO_NAME,,} /bids_dataset /outputs group
  # participant level tests for a longitudinal dataset
  - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test2:/bids_dataset -v ${HOME}/outputs2:/outputs bids/${REPO_NAME,,} /bids_dataset /outputs participant --participant_label 01
  - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test2:/bids_dataset -v ${HOME}/outputs2:/outputs bids/${REPO_NAME,,} /bids_dataset /outputs participant --participant_label 02
  # group level test for a longitudinal dataset
  - docker run -ti --rm --read-only -v /tmp:/tmp -v /var/tmp:/var/tmp -v ${HOME}/data/ds114_test2:/bids_dataset -v ${HOME}/outputs2:/outputs bids/${REPO_NAME,,} /bids_dataset /outputs group
